// Generated by scripts/gen-permissions.mjs from openapi.json. Do not edit.

/** Every permission a route in the API contract asks for. */
export type RoutePermission =
  | 'connection.manage'
  | 'data.read'
  | 'killswitch.resume'
  | 'killswitch.user'
  | 'lab.run'
  | 'mfa.recovery_codes'
  | 'notifications.manage'
  | 'operations.run'
  | 'password.change'
  | 'portfolio.manage'
  | 'portfolio.totals'
  | 'risk.global'
  | 'risk.reset'
  | 'strategy.promote'
  | 'tokens.manage'
  | 'tokens.revoke'
  | 'users.manage'
  | 'users.read';

/** `"METHOD /api/path/{param}"` to the permission the route needs. */
export const ROUTE_PERMISSIONS: Readonly<Record<string, RoutePermission>> = {
  'DELETE /api/auth/tokens/{token_id}': 'tokens.revoke',
  'DELETE /api/auth/users/{user_id}/mfa': 'users.manage',
  'DELETE /api/connections/{connection_id}': 'connection.manage',
  'DELETE /api/push/subscriptions': 'notifications.manage',
  'DELETE /api/studio/drafts/{draft_id}': 'lab.run',
  'DELETE /api/universes/{universe_id}': 'strategy.promote',
  'GET /api/auth/users': 'users.read',
  'GET /api/backups/jobs/{job_id}/result': 'risk.global',
  'GET /api/portfolio/totals': 'portfolio.totals',
  'PATCH /api/auth/users/{user_id}': 'users.manage',
  'PATCH /api/studio/drafts/{draft_id}': 'lab.run',
  'POST /api/auth/password': 'password.change',
  'POST /api/auth/recovery-codes': 'mfa.recovery_codes',
  'POST /api/auth/tokens': 'tokens.manage',
  'POST /api/auth/users': 'users.manage',
  'POST /api/auth/users/{user_id}/password': 'users.manage',
  'POST /api/backups': 'risk.global',
  'POST /api/connections/{connection_id}/link': 'portfolio.manage',
  'POST /api/connections/{connection_id}/sync': 'portfolio.manage',
  'POST /api/connections/keys': 'connection.manage',
  'POST /api/connections/portal': 'connection.manage',
  'POST /api/halts/{halt_id}/clear': 'risk.reset',
  'POST /api/halts/{halt_id}/resume': 'killswitch.resume',
  'POST /api/halts/kill': 'killswitch.user',
  'POST /api/ingest/runs': 'operations.run',
  'POST /api/jobs/{job_id}/cancel': 'lab.run',
  'POST /api/jobs/{job_id}/stream-token': 'data.read',
  'POST /api/lab/backtests': 'lab.run',
  'POST /api/lab/runs': 'lab.run',
  'POST /api/lab/signal-ic': 'lab.run',
  'POST /api/lab/sweeps': 'lab.run',
  'POST /api/notifications/read': 'notifications.manage',
  'POST /api/push/subscriptions': 'notifications.manage',
  'POST /api/schedule/{job}/run-now': 'operations.run',
  'POST /api/strategies/{strategy_id}/promote': 'strategy.promote',
  'POST /api/strategies/{strategy_id}/retire': 'strategy.promote',
  'POST /api/strategies/{strategy_id}/shadow': 'strategy.promote',
  'POST /api/studio/drafts': 'lab.run',
  'POST /api/studio/drafts/{draft_id}/backtests': 'lab.run',
  'POST /api/studio/drafts/{draft_id}/disable': 'strategy.promote',
  'POST /api/studio/drafts/{draft_id}/enable': 'strategy.promote',
  'POST /api/studio/drafts/{draft_id}/lab-runs': 'lab.run',
  'POST /api/studio/drafts/{draft_id}/register': 'strategy.promote',
  'POST /api/studio/drafts/{draft_id}/validate': 'lab.run',
  'POST /api/studio/spec/validate': 'lab.run',
  'POST /api/tca/orders/{client_id}/notes': 'portfolio.manage',
  'POST /api/ticks': 'operations.run',
  'POST /api/universes': 'lab.run',
  'POST /api/universes/{universe_id}/ensure': 'lab.run',
  'POST /api/universes/{universe_id}/refresh': 'lab.run',
  'POST /api/universes/index-history': 'lab.run',
  'PUT /api/notifications/preferences': 'notifications.manage',
  'PUT /api/notifications/quiet-hours': 'notifications.manage',
  'PUT /api/notifications/webhook': 'notifications.manage',
  'PUT /api/tca/notes/{note_id}': 'portfolio.manage',
};
